### PR TITLE
CDK Implementation

### LINKED ISSUE #8: Implement CDK
Ideally this will provide us with two methods for deployment:

1. AWS experienced users can deploy with the CDK CLI
2. Non-experienced users or those who just want something quick can do a one-click deploy with the slightly modified CloudFormation template we will generate.

This work is currently in progress, placing here to avoid duplicated efforts.

### PR DESCRIPTION
**Pull request by ryansonshine**
# CDK Implementation for minecraft-ondemand

This change contains the initial implementation for minecraft-ondemand.

[Usage](https://github.com/ryansonshine/minecraft-ondemand/blob/aws-cdk/cdk/README.md#usage)

### Functionality

- [x] Add CloudWatch trigger for the lambda
- [x] Integrate delegate zone setup
- [x] SNS/Twilio integration
- [x] Support for Java and Bedrock editions

### Bugs

- [x] Sort out task permissions errors
- [x] Investigate 3x event creation on lambda
- [x] Update retention settings for resources not removed by `cdk destroy`

### Customization

- [x] Parameterize additional settings
- [x] Add .env for configs
- [x] Optional resource creation/existing resource reuse

### Housekeeping

- [x] Swap out subs with Arn.format
- [x] Add "requireApproval": "never" to cdk.json

### Enhancements

- [x] Add handler for users not running docker
- [x] Add additional configs for [Minecraft Docker Server Docs](https://github.com/itzg/docker-minecraft-server/blob/master/README.md)

Closes #8

### CODE REVIEW

**Comment by doctorray117** [comment]
I think this looks really great.  I'm looking forward to testing it.  Is it worthwhile within documentation to have add a cdk step by step for those new to the process?  That's something I can work on once it's complete.  btw, main docs re-organized by me today, for both clarity and so that it works chronologically without having to jump back and forth.

**Comment by ryansonshine** [comment]
>  Is it worthwhile within documentation to have add a cdk step by step for those new to the process?

Definitely! By using the TypeScript version of CDK we're able to make it so that users essentially only need to have Node.js installed along with a valid AWS CLI profile. The quick start instructions will be something along the lines of customizing the configuration values and then running `npm run deploy`.

CDK will use `npx` to run the latest version of cdk without requiring any additional configuration or global installations from the user.

> btw, main docs re-organized by me today, for both clarity and so that it works chronologically without having to jump back and forth.

Excellent, I should be able to have a substantial update on Monday.

**Comment by ryansonshine** [comment]
@doctorray117 The current version works if you'd like to give it a try, there's a first pass at documentation [rendered here](https://github.com/ryansonshine/minecraft-ondemand/blob/aws-cdk/docs/CDK.md).

To give this one a try in it's current state you would do a git checkout then run:

```bash
DOMAIN_NAME="yourdomain.com"
SERVER_REGION="us-west-2"
npm run build && npm run deploy
```

This will create a hosted zone under `minecraft.yourdomain.com` and add an NS record to your hosted zone with "yourdomain.com" as it's domain.

**Comment by doctorray117** [comment]
I'll give it a shot this afternoon, thanks!

**Comment by doctorray117** [comment]
I couldn't wait.  And it worked the first try, awesome!  Here are my notes:

- I had to `export` the env vars before it would pick them up, because bash.  I'm sure the final method will be different anyway but I wanted to mention it.
- I love the use of ECR, though it requires having docker up and running locally, right?  I was going to have this method in the instructions but doing so would eliminate non-linux folks from participating so I hosted it on docker hub.  Should there be a config flag about building vs pulling the docker hub version?
- Great use of the delegate zone.
- In the launcher lambda it looks like the cloudwatch logs trigger is in there twice?  I only see it once in the subscription filters so I'm not sure why or if it's important.

As you get further along let's coordinate on documentation; I'd still like to present the manual methods for those who want to learn the ins and outs of the component services while offering a fantastic cdk quick start.  Maybe it's another page that's linked or we include it collapsed within this one, I'm not sure.  And with the incorporation of env vars in the lambda I'd need to either update the manual docs or maintain a second file within the tree.

Also looking at adjusting [connection monitoring](https://github.com/doctorray117/minecraft-ondemand/issues/11) alternatives to incorporate bedrock support, so when we get there we'd want server type to be a config flag.

Thanks again!

**Comment by ryansonshine** [comment]
Awesome!

>I had to export the env vars before it would pick them up, because bash. I'm sure the final method will be different anyway but I wanted to mention it.

Ah yeah, my latest change incorporates a `.env` file for configuration if you'd like to take a look.

[CDK.md - Setting configuration values](https://github.com/ryansonshine/minecraft-ondemand/blob/aws-cdk/docs/CDK.md#2-set-the-required-configuration-values)

[.env.sample](https://github.com/ryansonshine/minecraft-ondemand/blob/aws-cdk/.env.sample)

>I love the use of ECR, though it requires having docker up and running locally, right? I was going to have this method in the instructions but doing so would eliminate non-linux folks from participating so I hosted it on docker hub. Should there be a config flag about building vs pulling the docker hub version?

Great catch! I think I'll add a check to see if `docker` is on `PATH` so it can sort out whether or not to build locally. I'll add a configuration value for this as well.

>In the launcher lambda it looks like the cloudwatch logs trigger is in there twice? I only see it once in the subscription filters so I'm not sure why or if it's important.

Yeah I need to look closer into this; it appeared to only invoke once. Might not be important but something I'll definitely keep an eye on for fixing later.

>As you get further along let's coordinate on documentation; I'd still like to present the manual methods for those who want to learn the ins and outs of the component services while offering a fantastic cdk quick start. Maybe it's another page that's linked or we include it collapsed within this one, I'm not sure. And with the incorporation of env vars in the lambda I'd need to either update the manual docs or maintain a second file within the tree.

Sounds good! I've kept the docs for the CDK portion separate at docs/CDK.md so we can incorporate that however we think would be best for users.

> Also looking at adjusting connection monitoring alternatives to incorporate bedrock support, so when we get there we'd want server type to be a config flag.

Cool, I've added this to the TODO.md under enhancements

**Comment by ryansonshine** [comment]
@doctorray117 this one is ready for review/merge when you get a chance. I'll have time next week for the additional enhancements.

**Comment by Xcalllibur** [comment]
Great job @ryansonshine - looks like I started my implementation around the same time and I only just saw this PR - unfortunate, as I spent quite a bit of time this week on it.  Anyway my fully working CDK implementation is in [PR#19](https://github.com/doctorray117/minecraft-ondemand/pull/19).  Haven't found any issues thus far - hopefully it is of some use to you @doctorray117.

**Comment by doctorray117** [comment]
Hi @ryansonshine some questions based on my in-progress review..

- Is it reasonable to put all of the cdk scripts within a `cdk` folder or no? Just for organizational purposes and a quick visual from a first time visitor that there is a cdk option without having to parse a long list or read far in the readme.
- Currently calling for aws-cdk-lib 2.0.0-rc.14; looks like they're close to 2.0.0 but not quite yet; should there be a ~ or whatever to keep it current?  I'm not sure what the best practices are on immediate pre-release stuff, though I guess we can always come back in a few weeks and update it when it's gold.
- Do you think I should incorporate the lambda env vars into the manual version?
- I would have additional edits for the README to point at the CDK specific readme, a couple of sentences on quick start, etc.  I think I would be safe to add them after the fact? Or is it better to PR back to your branch first?

Thanks!

**Comment by ryansonshine** [comment]
Great questions @doctorray117 !

> * Is it reasonable to put all of the cdk scripts within a `cdk` folder or no? Just for organizational purposes and a quick visual from a first time visitor that there is a cdk option without having to parse a long list or read far in the readme.

Yeah, that's entirely reasonable. I'll make the changes in the directory structure for this PR; after it's merged can you comb through the docs to make sure they still make sense? (I just started paternity leave a couple of days ago so my hands-on time will be limited).

> * Currently calling for aws-cdk-lib 2.0.0-rc.14; looks like they're close to 2.0.0 but not quite yet; should there be a ~ or whatever to keep it current?  I'm not sure what the best practices are on immediate pre-release stuff, though I guess we can always come back in a few weeks and update it when it's gold.

I'll put in a follow-up change as new versions are released, for now, I think it's best to pin it to an exact version that we know works, especially for users who are not familiar with CDK. 

> * Do you think I should incorporate the lambda env vars into the manual version?

I think the best route forward for users with and without experience could be to have the same hardcoded values at the top that end up getting used as default values for when env vars are not found. I'll put in a change in this PR to the function code; if you have time to update the relevant documentation that would be great.

> * I would have additional edits for the README to point at the CDK specific readme, a couple of sentences on quick start, etc.  I think I would be safe to add them after the fact? Or is it better to PR back to your branch first?

I agree we can just add them after the fact.

**Comment by doctorray117** [comment]
Perfect, I'll complete my review and let you know if I have any other questions and get stuff merged shortly.  Also congratulations and good luck!

**Review by doctorray117 — APPROVED** [review]

**Comment by doctorray117** [comment]
@ryansonshine did you end up taking the nat gateway out? I just got my $38 bill for my test account last month from my first test before the PR was ready.

**Comment by ryansonshine** [comment]
> @ryansonshine did you end up taking the nat gateway out? I just got my $38 bill for my test account last month from my first test before the PR was ready.

@doctorray117 Yeah it's been removed. If you redeploy and go to the Elastic IP list in the console it should be empty.

**Pull request merged**
