### PR TITLE
Add Bedrock Edition information to instructions

### PR DESCRIPTION
**Pull request by safetymonkey**
Update README.md to include alternate information for Bedrock edition.

### CODE REVIEW

**Comment by doctorray117** [comment]
I think I've found a way to check for active connections on bedrock by using and/or modeling after itzg/mc-monitor.  Switching to this method to determine if players are online is probably superior to the current netstat.  I'll work on this a bit over the weekend.

**Comment by safetymonkey** [comment]
Sorry for submitting the PR without updating the watchdog, it didn't occur to me that wouldn't work. I'm a little rusty on Docker, but I think the `itzg/mc-monitor` solution would work great.

When the server is still starting up:
``` zsh
$ docker run -it --rm itzg/mc-monitor status-bedrock --host my-mc-host.com
2021/09/13 16:56:19 failed to query bedrock server my-mc-host.com:19132: ping raknet: context deadline exceeded
```

Once the server has launched (nobody online):
```zsh
$ docker run -it --rm itzg/mc-monitor status-bedrock --host my-mc-host.com
my-mc-host.com:19132 : version=1.17.11 online=0 max=10%
```

I'll try to play around with this more and see if I can get your watchdog code running. The thing I still need to figure out is running docker-within-docker.

**Comment by doctorray117** [comment]
I think we're on the same line of thinking, I [opened an issue](https://github.com/doctorray117/minecraft-ondemand/issues/11) to discuss it.

ecs/fargate can't do docker-in-docker unfortunately, but we can use the mc-monitor program directly by running the `go get` as part of the dockerfile and then using the program to query the local server without issue.  The primary concern, which isn't a _huge_ deal but it of note is that it increases the size of the container significantly.

I was going to try and analyze the ping message from a bedrock client to see if it's something that's easy enough to replicate with socat instead, which would keep our size down.  I think it's worth a brief look before integrating mc-monitor in directly.

If the socat route doesn't work, then maybe I'd offer a bedrock specific version of the watchdog so that java users don't need to use the giant container.  What do you think?

**Comment by doctorray117** [comment]
I've got a feature/bedrock branch that will include these and other relevant changes, that will be merged after further testing.  Closing this PR.  Thanks.

**Pull request closed without merging**
