### PR TITLE
CDK application to deploy on-demand Minecraft resources

### PR DESCRIPTION
**Pull request by Xcalllibur**
**Implemented**
* CDK application that automatically deploys all required resources, based on configuration
* Optionally deploys the tasks to sync EFS <-> S3
* Detailed README that describes how to setup, configure and deploy the CDK application

**Features Not Implemented**
* Support for Twilio (i.e. setting environment variables)
* Support for Bedrock
* Ability to deploy multiple servers to the same account (i.e. add a prefix to all resources)

### CODE REVIEW

**Comment by Xcalllibur** [comment]
@doctorray117 do you think you will review this PR?  Looks like you are focused on the other CDK implementation so even though most of the issues are already addressed here, it seems unlikely it will be merged in.  If that's the case I'm happy to close and can continue in my own repo if you like.

**Comment by doctorray117** [comment]
Hey, I would like to look at it still, just haven't had a free moment because of work.. Please leave it open for at least another day or two.  Yes, I am planning on bringing the other one in as I've been working on it with him, though I would like to review yours and even if I don't merge it in directly alongside the other as a secondary option I'd absolutely link to your work within the main docs.

**Comment by ryansonshine** [comment]
Hi @Xcalllibur !

Thanks for your contribution! As a general rule of thumb when contributing to open source, it's generally best to reach out to ensure you won't be duplicating work prior to doing large features. 

> so even though most of the issues are already addressed here

We de-prioritized adding the EFS -> S3 DataSync and optional billing alert to focus on other core functionality we felt would be more important to help users who weren't as familiar with AWS to get up and running with as few steps as possible which is why we added the functionality for creating the delegated zone as well as the required logging for DNS queries.

After we merge #9 and open up an issue for implementing EFS -> S3 DataSync if you'd like to take on this assignment please let us know as I think you've done a great job with your implementation. 😃

**Comment by ryansonshine** [comment]
Closing due to this already being implemented.

**Pull request closed without merging**
